### ISSUE TITLE
default cache name cannot be loaded

### ISSUE THREAD

**Issue by evtk** [Polyneue/gulp-asset-cache#2]
hey,

```
        if (!cacheName) {
            assetCache.cacheName = './.asset-cache';
        } else {
            assetCache.cacheName = cacheName;
        }

        // Try to load an existing cache file
        try {
            assetCache.cacheFile = JSON.parse(fs.readFileSync(cacheName));
        } catch (err) {
            assetCache.cacheFile = {};
        }
```

JSON.parse(fs.readFileSync(cacheName))
cacheName stays undefined if you have not set a custom cacheName.

**Comment by Polyneue** [comment]
Thanks for pointing this out, we changed our site structure to better handle diffing with some other modules at work so I haven't had time to revisit this module. I'll push a bugfix up when I get a chance. 

``` js
try {
    assetCache.cacheFile = JSON.parse(fs.readFileSync(assetCache.cacheName));
} catch (err) {
    assetCache.cacheFile = {}
}
```

Updating to use the `assetCache.cacheName` should resolve the undefined issue since it's already tested for in the if statement above loading the cache file.

**Comment by evtk** [comment]
Great, thanks for fixing this one (y).
